//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSNDBEntities : DbContext
    {
        public CSNDBEntities()
            : base("name=CSNDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblAccountList> TblAccountLists { get; set; }
        public DbSet<tblAccountType> tblAccountTypes { get; set; }
        public DbSet<TblAccountTypeMaster> TblAccountTypeMasters { get; set; }
        public DbSet<TblAcctStatu> TblAcctStatus { get; set; }
        public DbSet<TblContactStatu> TblContactStatus { get; set; }
        public DbSet<TblCSNGroup> TblCSNGroups { get; set; }
        public DbSet<TblCSNList> TblCSNLists { get; set; }
        public DbSet<TBLCSNRoleAccess> TBLCSNRoleAccesses { get; set; }
        public DbSet<TblCSNType> TblCSNTypes { get; set; }
        public DbSet<TblCustType> TblCustTypes { get; set; }
        public DbSet<TblDivision> TblDivisions { get; set; }
        public DbSet<TblGeneralActivitie> TblGeneralActivities { get; set; }
        public DbSet<TblInitiativeList> TblInitiativeLists { get; set; }
        public DbSet<TblInitiativeResult> TblInitiativeResults { get; set; }
        public DbSet<TblInitStatu> TblInitStatus { get; set; }
        public DbSet<TblInitType> TblInitTypes { get; set; }
        public DbSet<tblLineStatu> tblLineStatus { get; set; }
        public DbSet<TblMfgContactMaster> TblMfgContactMasters { get; set; }
        public DbSet<TblMfgList> TblMfgLists { get; set; }
        public DbSet<TBLMfgPlatform> TBLMfgPlatforms { get; set; }
        public DbSet<TblMfg> TblMfgs { get; set; }
        public DbSet<TblMfgState> TblMfgStates { get; set; }
        public DbSet<TblPlatform> TblPlatforms { get; set; }
        public DbSet<TblResponseType> TblResponseTypes { get; set; }
        public DbSet<tblRoleMaster> tblRoleMasters { get; set; }
        public DbSet<TblState> TblStates { get; set; }
        public DbSet<TblTerritory> TblTerritories { get; set; }
        public DbSet<SeeAccountsWithNOTerritory> SeeAccountsWithNOTerritories { get; set; }
        public DbSet<SeeBuyersLinesThatdoNOtexistInMFGList> SeeBuyersLinesThatdoNOtexistInMFGLists { get; set; }
        public DbSet<SeeGeneralActivitiesWithNoContact> SeeGeneralActivitiesWithNoContacts { get; set; }
        public DbSet<Vw_CSN_Account_Buyers> Vw_CSN_Account_Buyers { get; set; }
        public DbSet<Vw_Mfg_CSN_Account_Buyer> Vw_Mfg_CSN_Account_Buyer { get; set; }
        public DbSet<Vw_Mfg_Initiative_List> Vw_Mfg_Initiative_List { get; set; }
        public DbSet<vwAccountList> vwAccountLists { get; set; }
        public DbSet<vwBuyersList> vwBuyersLists { get; set; }
        public DbSet<vwMFGAccount> vwMFGAccounts { get; set; }
        public DbSet<vwMFGContact> vwMFGContacts { get; set; }
        public DbSet<VwMfgPlatform> VwMfgPlatforms { get; set; }
        public DbSet<tblPageMaster> tblPageMasters { get; set; }
        public DbSet<TblRolePageMapping> TblRolePageMappings { get; set; }
        public DbSet<TblpkInitResult> TblpkInitResults { get; set; }
        public DbSet<TblContactMaster> TblContactMasters { get; set; }
        public DbSet<TblBuyersLineCarry> TblBuyersLineCarries { get; set; }
    }
}
