//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeeGeneralActivitiesWithNoContact
    {
        public int ActivityItemCode { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Subline { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string Expr2 { get; set; }
    }
}
