//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBuyersLineCarry
    {
        public int BLCId { get; set; }
        public int ContactID { get; set; }
        public Nullable<bool> CarryLine { get; set; }
        public string PlatformID { get; set; }
    }
}
