//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCSNList
    {
        public TblCSNList()
        {
            this.TblGeneralActivities = new HashSet<TblGeneralActivitie>();
        }
    
        public int CSNID { get; set; }
        public int CSNTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string SortName { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Dept { get; set; }
        public Nullable<int> CSNGroupID { get; set; }
        public string Email { get; set; }
        public string GsmEmail { get; set; }
        public string DirEmail { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Cell { get; set; }
        public string AltNumber { get; set; }
        public string Fax { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string FlagFollowups { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SAddress1 { get; set; }
        public string SAddress2 { get; set; }
        public string SCity { get; set; }
        public string SState { get; set; }
        public string SCountry { get; set; }
        public string SZip { get; set; }
        public Nullable<int> Roleid { get; set; }
        public string Division { get; set; }
    
        public virtual ICollection<TblGeneralActivitie> TblGeneralActivities { get; set; }
    }
}
