//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInitiativeList
    {
        public TblInitiativeList()
        {
            this.TblInitiativeResults = new HashSet<TblInitiativeResult>();
        }
    
        public int InitiativeID { get; set; }
        public string MfgID { get; set; }
        public Nullable<int> InitiativeType { get; set; }
        public string InitiativeLabel { get; set; }
        public string InitiativeDesc { get; set; }
        public string InitiativeIncentive { get; set; }
        public Nullable<System.DateTime> InitiativeDate { get; set; }
        public Nullable<System.DateTime> InitiativeDoneBy { get; set; }
        public string InitiativeRequestedBY { get; set; }
        public string InitStatusID { get; set; }
    
        public virtual TblInitType TblInitType { get; set; }
        public virtual TblMfg TblMfg { get; set; }
        public virtual ICollection<TblInitiativeResult> TblInitiativeResults { get; set; }
    }
}
