//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLineStatu
    {
        public int StatusItemCode { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string MfgID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ReportTitleLine1 { get; set; }
        public string ReportTitleLine2 { get; set; }
        public string LineStatus { get; set; }
        public Nullable<bool> NewEntry { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
