//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMfgList
    {
        public string SubLine { get; set; }
        public string MfgID { get; set; }
        public string SublineDesc { get; set; }
        public string MFGPrintName { get; set; }
        public Nullable<bool> MfgActive { get; set; }
        public Nullable<bool> DryOnly { get; set; }
        public Nullable<bool> FrozenFoods { get; set; }
        public Nullable<bool> Food { get; set; }
        public string ItemListTableID { get; set; }
        public Nullable<bool> NewEntry { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> StatusChange { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
