//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblpkInitResult
    {
        public TblpkInitResult()
        {
            this.TblInitiativeResults = new HashSet<TblInitiativeResult>();
        }
    
        public int InitResultID { get; set; }
        public Nullable<int> ResponseType { get; set; }
        public string Response { get; set; }
        public string Status { get; set; }
        public Nullable<int> Category { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual ICollection<TblInitiativeResult> TblInitiativeResults { get; set; }
        public virtual TblResponseType TblResponseType { get; set; }
    }
}
