//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblResponseType
    {
        public TblResponseType()
        {
            this.TblpkInitResults = new HashSet<TblpkInitResult>();
        }
    
        public int ResponseTypeID { get; set; }
        public string ResponseType { get; set; }
    
        public virtual ICollection<TblpkInitResult> TblpkInitResults { get; set; }
    }
}
