//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTerritory
    {
        public string Territory { get; set; }
        public string TerrDesc { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
