//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_CSN_Account_Buyers
    {
        public int CSNID { get; set; }
        public string CSNName { get; set; }
        public int AccountCode { get; set; }
        public string Company { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string BuyersName { get; set; }
        public string BuyersFirstName { get; set; }
        public Nullable<bool> AccountDryOnly { get; set; }
        public Nullable<bool> AccountFreezer { get; set; }
        public Nullable<bool> AccountFood { get; set; }
    }
}
