//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Mfg_Initiative_List
    {
        public string MfgID { get; set; }
        public string MfgName { get; set; }
        public int InitiativeID { get; set; }
        public string InitiativeLabel { get; set; }
        public string InitTypeDesc { get; set; }
        public string InitiativeDesc { get; set; }
        public Nullable<System.DateTime> InitiativeDate { get; set; }
    }
}
