//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAccountList
    {
        public string CSNID { get; set; }
        public string CSNRep { get; set; }
        public int AccountCode { get; set; }
        public string Company { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyExt { get; set; }
        public string CompanyFax { get; set; }
        public Nullable<bool> DryOnly { get; set; }
        public Nullable<bool> Freezer { get; set; }
        public Nullable<bool> Food { get; set; }
        public Nullable<int> NumStores { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToMailCode { get; set; }
        public string CustType1 { get; set; }
        public string CustType2 { get; set; }
        public string TypeName { get; set; }
        public string StateName { get; set; }
        public string ShippingState { get; set; }
        public string Territory { get; set; }
        public string TerritoryID { get; set; }
        public string Platforms { get; set; }
        public string PlatformID { get; set; }
    }
}
