//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBuyersList
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CellNumber { get; set; }
        public string ContactEmail { get; set; }
        public string ContactTitle { get; set; }
        public string Department { get; set; }
        public string FaxNumber { get; set; }
        public string MailAddress1 { get; set; }
        public string MailAddress2 { get; set; }
        public string MailCity { get; set; }
        public string MailCountry { get; set; }
        public string PhoneExt { get; set; }
        public string OfficePhone { get; set; }
        public string LineAssignment { get; set; }
        public int AccountCode { get; set; }
        public string Company { get; set; }
        public string MailState { get; set; }
        public string MailMailCode { get; set; }
    }
}
