//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMFGContact
    {
        public int AccountCode { get; set; }
        public string Company { get; set; }
        public string Division { get; set; }
        public string DivisionName { get; set; }
        public int ContactID { get; set; }
    }
}
