//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwMfgPlatform
    {
        public int MfgPlatformID { get; set; }
        public string MfgName { get; set; }
        public string Platform { get; set; }
        public string PlatformID { get; set; }
        public string MfgID { get; set; }
    }
}
